### ISSUE TITLE
Attribute Error:

### ISSUE THREAD

**Issue by nthakor** [cmgreen210/TensorFlowDeepAutoencoder#2]
When I tried to run the program using `python  code/run.py` in terminal it showed following error: 

`Traceback (most recent call last):
  File "code/run.py", line 41, in <module>
    main()
  File "code/run.py", line 37, in main
    ae = autoencoder.main_unsupervised()
  File "/home/nilay/gdrive/REU/TensorFlowDeepAutoencoder/code/ae/autoencoder.py", line 303, in main_unsupervised
    loss = loss_x_entropy(layer, target_for_loss)
  File "/home/nilay/gdrive/REU/TensorFlowDeepAutoencoder/code/ae/autoencoder.py", line 258, in loss_x_entropy
    net_output_tf = tf.ops.convert_to_tensor(output, name='input')
AttributeError: 'module' object has no attribute 'ops'
`

I have followed all the installation steps explained in README.md

**Comment by cmgreen210** [comment]
Hmmm...gonna need some more info. What system are you running? Did you make sure to activate the Python virtualenv?

**Comment by nthakor** [comment]
I activated virtualenv. Error resolved. Thanks

**Comment by xiximeng** [comment]
I have got the same problem,but I don not konw the reason why should I activate the Python virtualenv? I am using Ubuntu14.04
